---
title: "Beta part"
author: "Colin J. Brislawn"
date: "February 10, 2025"
output:
  html_document:
    toc: true
---

```{r setup0, include=T}
library("tidyverse")
library("DT")

library("vegan")
library("betapart")

knitr::opts_chunk$set(echo = TRUE, cache = TRUE)

theme_set(theme_bw())
theme_update(
  strip.background = element_blank()
  # axis.text.x = element_text(angle = -20, hjust = 0)
)
```

```{r lint, include=F, eval=T}
library(styler)
style_dir(strict = TRUE)

library(lintr)
lintr::lint("betapart.Rmd",
  linters = linters_with_defaults(
    # line_length_linter = line_length_linter(120),
    object_name_linter = NULL,
    commented_code_linter = NULL
  )
)
```

```{r betapart}
# Feature table binary
ftab_b <- read_tsv("feature_table_binary.tsv", skip = 1, col_names = T) |>
  column_to_rownames(var = "#OTU ID") |>
  t()
# Transpose because taxa_are_rows in Qiime2 and betapart wants a
# "data frame, where rows are sites and columns are species"

ftab_b_bp <- beta.pair(ftab_b, index.family = "jaccard")
ftab_b_bp |> glimpse()
```

```{r testdist}
if (
  any(is.na(ftab_b_bp$beta.jac))
) {
  stop("NAs in the matrix")
}
if (
  any(ftab_b_bp$beta.jac < 0)
) {
  stop("Negative distances produced!")
}

# Check nestedness
dist_matrix <- as.matrix(ftab_b_bp$beta.jne) # Convert to a regular matrix

if (any(is.na(dist_matrix))) stop("NAs in the matrix")
if (any(dist_matrix < 0)) stop("Negative distances produced!")

# 1. Ensure Symmetry
if (!isSymmetric(dist_matrix)) stop("Not symmetric")

# 2. Ensure Diagonal is Zero
if (any(diag(dist_matrix) != 0)) stop("The diagonal is NOT all zeros!\n")

# 3. Triangle Inequality (Most computationally intensive)
triangle_check <- function(dist_matrix) {
  n <- nrow(dist_matrix)
  for (i in 1:n) {
    for (j in 1:n) {
      for (k in 1:n) {
        if (dist_matrix[i, j] + dist_matrix[j, k] >= dist_matrix[i, k]) {
          # All good!
        } else { # Violation
          cat("Triangle inequality violated at: [", i, ", ", j, ", ", k, "]\n", sep = "")
          cat(dist_matrix[i, j], " + ", dist_matrix[j, k], " <= ", dist_matrix[i, k], "\n", sep = "")
          cat(dist_matrix[i, j] + dist_matrix[j, k], " <= ", dist_matrix[i, k], "\n", sep = "")
          return(FALSE) # Stop at the first violation
        }
      }
    }
  }
  return(TRUE) # No violations found
}
# ftab_b_bp$beta.jac |> as.matrix() |> triangle_check() # passes!
ftab_b_bp$beta.jne |>
  as.matrix() |>
  triangle_check()
ftab_b_bp$beta.jtu |>
  as.matrix() |>
  triangle_check()
```

Let's use the `vegan::adonis` test to see how much variation of nestedness and
turnover can be attributed to a metadata variable.

Note that while Jaccard distances of nestedness and turnover add up to
total Jaccard distance, these R2 values will not sum up.

Rather, this qualitative measurement shows what correlates best.

```{r adonis2}
meta_all <- read_tsv("sample-metadata.tsv", comment = "#")

# Filter to keep samples that are in our feature table
meta <- meta_all |> filter(SampleID %in% rownames(ftab_b))
meta |> glimpse()

adonis2_on_bplist <- function(formula_rhs, meta, bp_list) {
  rbind(
    adonis2(
      as.formula(paste("bp_list$beta.jac ~", formula_rhs)),
      data = meta, permutations = 999
    ) |>
    rownames_to_column() |>
    tibble(test = formula_rhs, dist = "Jaccard Total")
    # Can use these with ADONIS2 because they are not true distances. They don't satisfy the triangle inequality.
    # adonis2(as.formula(paste("bp_list$beta.jtu ~", formula_rhs)),
    #   data = meta, permutations = 999
    #   ) |> rownames_to_column() |> tibble(test = formula_rhs, dist = "Jaccard Turnover"),
    # adonis2(as.formula(paste("bp_list$beta.jne ~", formula_rhs)),
    #   data = meta, permutations = 999
    #   ) |> rownames_to_column() |> tibble(test = formula_rhs, dist = "Jaccard Nestedness")
  ) |>
    filter(rowname == "Model") |>
    select(-rowname) |>
    relocate(test, dist)
}

# Example Usage
ftab_b_bp_adonis <- rbind(
  adonis2_on_bplist("PatientID", meta, ftab_b_bp),
  adonis2_on_bplist("Disease", meta, ftab_b_bp),
  adonis2_on_bplist("Timepoint", meta, ftab_b_bp),
  adonis2_on_bplist("Disease + Timepoint", meta, ftab_b_bp),
  adonis2_on_bplist("Timepoint + Disease", meta, ftab_b_bp),
  adonis2_on_bplist("autoFmtGroup", meta, ftab_b_bp)
)
```

```{r adonis2plots}
ftab_b_bp_adonis |> datatable(rownames = FALSE)

ftab_b_bp_adonis |> ggplot(aes(x = test, y = R2)) +
  geom_col(position = "dodge") +
  coord_flip() +
  labs(
    # title = "Variance Explained by metadata variables",
    y = "ADONIS R² value (fraction of variation explained)")


```

```{r, include=F, eval=F}
rmarkdown::render("betapart.Rmd")
# To clear cache
unlink("betapart_cache/")
```

```{r distmelt, eval = F, include = F}
distmelt <- function(d) {
  d.melt <- d %>%
    as.matrix() %>%
    as.data.frame() %>%
    tibble::rownames_to_column() %>%
    melt()
  d.melt$variable <- as.character(d.melt$variable)
  return(d.melt[d.melt$variable > d.melt$rowname, ])
}
```
